#!/usr/bin/python -u
#encoding: utf-8

import sys, getopt
import redis
import threading
import gevent.select
from time import sleep
from Queue import Queue, Empty
from datetime import datetime
from redisweeds.weed import RedisWeed

REDIS_HOST = "127.0.0.1"
REDIS_PORT = "6379"
WEEDS_HOST = "127.0.0.1"
WEEDS_PORT = "9333"

EXPIRE_EVENTS = "__keyevent@0__:expired"

EXPIRE_KEYS = Queue()

class ExpireThread(threading.Thread):

    def __init__(self):
        super(ExpireThread, self).__init__()
        self.over = False

    def dismiss(self):
        self.over = True

    def run(self):
        while not self.over:
            try:
                ex_key = EXPIRE_KEYS.get(timeout=3)
            except Empty:
                continue

            conn = redis.StrictRedis(REDIS_HOST, REDIS_PORT)
            try:
                fileid = conn.get("shadow:%s"%ex_key)
            except redis.exceptions.ConnectionError:
                print "[%s]" % datetime.now().strftime("%m-%d %H:%M:%S"), "redis连接失败(%s:%s), 2秒后重试..."%(REDIS_HOST, REDIS_PORT)
                EXPIRE_KEYS.put(ex_key)
                sleep(2)
                continue

            if not fileid:
                continue

            rd = RedisWeed(REDIS_HOST, REDIS_PORT, WEEDS_HOST, WEEDS_PORT)
            rd.delete_file(fileid)
            conn.delete("shadow:%s"%ex_key)
            print "[%s]" % datetime.now().strftime("%m-%d %H:%M:%S"), "删除过期文件，FILEKEY: %s, FILEID: %s"%(ex_key, fileid)


def createRedisChannel(wait_timeout=1):
    try:
        conn = redis.StrictRedis(REDIS_HOST, REDIS_PORT)
        chan = conn.pubsub()
        chan.subscribe(EXPIRE_EVENTS)
        print "[%s]"%datetime.now().strftime("%m-%d %H:%M:%S"), "redis连接成功(%s:%s)"%(REDIS_HOST, REDIS_PORT)
        return chan
    except redis.exceptions.ConnectionError:
        print "[%s]"%datetime.now().strftime("%m-%d %H:%M:%S"), "redis连接失败(%s:%s), 第%d次重新连接..."%(REDIS_HOST, REDIS_PORT, wait_timeout)
        sleep(wait_timeout)
        return createRedisChannel(wait_timeout+1)


def listenExpireEvent():
    chan = createRedisChannel()
    expire_fd = chan.connection._sock.fileno()
    while True:
        ready = gevent.select.select([expire_fd], [], [])
        if expire_fd in ready[0]:
            try:
                msg = chan.get_message()
                if msg.get("type")=="message" and msg.get("channel")=="__keyevent@0__:expired":
                    EXPIRE_KEYS.put(msg.get("data"))
            except redis.exceptions.ConnectionError:
                listenExpireEvent()


if __name__ == "__main__":
    argv = sys.argv[1:]

    opts, args = getopt.getopt(argv, "a:b:c:d:", [
        "redis-addr=",
        "redis-port=",
        "weeds-addr=",
        "weeds-port="
    ])

    if len(opts) != 4:
        print "listen_expire --redis-addr=<redis_addr> --redis-port=<redis_port> --weeds-addr=<weeds_addr> --weeds-port=<weeds_port>"
        sys.exit(1)

    for opt, arg in opts:
        if opt in ("-a", "--redis-addr"):
            REDIS_HOST = arg
        elif opt in ("-b", "--redis-port"):
            REDIS_PORT = arg
        elif opt in ("-c", "--weeds-addr"):
            WEEDS_HOST = arg
        elif opt in ("-d", "--weeds-port"):
            WEEDS_PORT = arg

    for _ in range(3):
        ExpireThread().start()

    print "[%s]"%datetime.now().strftime("%m-%d %H:%M:%S"), "监听服务已启动..."
    listenExpireEvent() 
